name: env-secrets
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: get-secret
        env:
          MYSECRET: ${{secrets.FIRST_SECRET}}
        run: echo "Hello Developer! The actual secret is $MYSECRET" 
